# Generated by Django 6.0.3 on 2026-05-15 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nni', models.CharField(blank=True, max_length=50)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('nationalite', models.CharField(blank=True, default='MRT', max_length=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='kyc/%Y/%m/%d/')),
                ('donnees_brutes', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_cours', 'Vérification en cours'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='non_soumis', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification KYC',
                'verbose_name_plural': 'Vérifications KYC',
            },
        ),
    ]
