# Generated by Django 6.0.3 on 2026-05-15 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_kycverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='statut',
            field=models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_cours', 'En cours de vérification'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='non_soumis', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
    ]
