# Generated by Django 6.0.3 on 2026-05-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_kycverification_statut_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KYCVerification',
        ),
    ]
