# Generated by Django 6.0.3 on 2026-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_delete_kycverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='face_image_document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='face_similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='kyc_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='kyc_document_type',
            field=models.CharField(blank=True, choices=[('cni', 'Carte Nationale'), ('passport', 'Passeport'), ('sejour', 'Carte de Séjour')], max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ocr_done', 'OCR terminé'), ('face_done', 'Face ID vérifié'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nationality',
            field=models.CharField(blank=True, default='MRT', max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nni',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='selfie_profil',
            field=models.ImageField(blank=True, null=True, upload_to='media/selfies/'),
        ),
    ]
