# Generated by Django 6.0.3 on 2026-05-15 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_utilisateur_birth_date_utilisateur_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('auth_type', models.CharField(default='email', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
