# Generated by Django 6.0.3 on 2026-05-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_kycverificationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverificationsession',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
