# Generated by Django 6.0.3 on 2026-05-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_kycverificationsession_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='document_full_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
