# Generated by Django 6.0.3 on 2026-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_utilisateur_document_full_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='father_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
