# Generated by Django 6.0.3 on 2026-06-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_utilisateur_father_name_utilisateur_father_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_kyc_validated',
            field=models.BooleanField(default=False),
        ),
    ]
