# Generated by Django 6.0.3 on 2026-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_utilisateur_is_kyc_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_kyc_validated',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='kyc_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ocr_done', 'OCR terminé'), ('face_done', 'Face ID vérifié'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('skipped', 'Ignoré')], default='pending', max_length=20),
        ),
    ]
