# Generated by Django 6.0.3 on 2026-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_remove_utilisateur_is_kyc_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='kyc_skipped_at',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ocr_done', 'OCR terminé'), ('face_done', 'Face ID vérifié'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
