# Generated by Django 6.0.3 on 2026-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0012_remove_utilisateur_kyc_skipped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverificationsession',
            name='from_visitor_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverificationsession',
            name='visitor_session_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_visiteur',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est en mode exploration (visiteur)"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='session_visiteur_expire',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de la session visiteur", null=True),
        ),
    ]
