# Generated by Django 6.0.3 on 2026-07-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgetdepense'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
