# Generated by Django 6.0.3 on 2026-04-24 00:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('essai', 'Essai'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='essai', max_length=10)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('en_attente', 'En attente')], default='actif', max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Abonnement',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('methode', models.CharField(default='mobile_money', max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué')], default='en_attente', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('essai', 'Essai Gratuit'), ('standard', 'Standard'), ('entreprise', 'Entreprise')], max_length=20, unique=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nb_categories_max', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
