# Generated by Django 6.0.3 on 2026-06-20 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEncaissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('methode', models.CharField(choices=[('rssbank', 'RSSBank'), ('trackpay', 'TrackPay')], max_length=20, unique=True)),
                ('numero_compte', models.CharField(max_length=100)),
                ('nom_titulaire', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Compte d'encaissement",
                'verbose_name_plural': "Comptes d'encaissement",
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='capture_ecran',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='raison_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_abonnement_demande',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_utilisateur_demande',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('entreprise', 'Entreprise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('rssbank', 'RSSBank'), ('trackpay', 'TrackPay')], default='mobile_money', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('refuse', 'Refusé')], default='en_attente', max_length=15),
        ),
    ]
