# Generated by Django 6.0.3 on 2026-06-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0003_compteencaissement_paiement_capture_ecran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reference_trackpay',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compteencaissement',
            name='methode',
            field=models.CharField(choices=[('rssbank', 'RSSBank'), ('sedad', 'Sedad'), ('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('trackpay', 'TrackPay')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('rssbank', 'RSSBank'), ('sedad', 'Sedad'), ('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('trackpay', 'TrackPay')], default='mobile_money', max_length=50),
        ),
    ]
