# Generated by Django 6.0.3 on 2026-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0004_paiement_reference_trackpay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='nb_renouvellements',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_renouvellement',
            field=models.CharField(blank=True, choices=[('nouveau', 'Nouveau (depuis essai/expiré)'), ('prolongation', 'Prolongation (même plan)'), ('changement', 'Changement de plan autorisé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('essai', 'Essai'), ('mensuel', 'Mensuel'), ('2_mois', '2 Mois'), ('3_mois', '3 Mois'), ('6_mois', '6 Mois'), ('annuel', 'Annuel')], default='essai', max_length=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_abonnement_demande',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('2_mois', '2 Mois'), ('3_mois', '3 Mois'), ('6_mois', '6 Mois'), ('annuel', 'Annuel')], max_length=10, null=True),
        ),
    ]
