# Generated by Django 6.0.3 on 2026-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0005_abonnement_nb_renouvellements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['ordre_affichage', 'nom'], 'verbose_name': 'Plan'},
        ),
        migrations.AddField(
            model_name='abonnement',
            name='date_expiration_demo',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de la démo (si limitée dans le temps)", null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='est_demo',
            field=models.BooleanField(default=False, help_text="Indique si c'est un abonnement de démonstration"),
        ),
        migrations.AddField(
            model_name='plan',
            name='est_demo',
            field=models.BooleanField(default=False, help_text='Plan réservé à la démonstration'),
        ),
        migrations.AddField(
            model_name='plan',
            name='ordre_affichage',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans l'interface"),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('en_attente', 'En attente'), ('demo', 'Démo / Visiteur')], default='actif', max_length=15),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('essai', 'Essai'), ('mensuel', 'Mensuel'), ('2_mois', '2 Mois'), ('3_mois', '3 Mois'), ('6_mois', '6 Mois'), ('annuel', 'Annuel'), ('demo', 'Démo / Visiteur')], default='essai', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nom',
            field=models.CharField(choices=[('essai', 'Essai Gratuit'), ('standard', 'Standard'), ('entreprise', 'Entreprise'), ('demo', 'Démo / Visiteur')], max_length=20, unique=True),
        ),
    ]
